# This workflow makes sure edge case versions work
name: Test Installation

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/**.yml"

jobs:
  test-installation:
    strategy:
      max-parallel: 48
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7.5, 3.7, 3.8, 3.9]
        torch-version: [1.8.0, 1.8.1, 1.9.0, 1.9.1]
        # include:
        #   - os: windows-latest
        #     python-version: 3.9
        #     torch-version: 1.7.1
        #   - os: ubuntu-latest
        #     python-version: 3.9
        #     torch-version: 1.7.1
        #   - os: macos-latest
        #     python-version: 3.9
        #     torch-version: 1.7.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install PyTorch Linux and MacOS
        if: startsWith(runner.os, 'Windows') != true
        run: |
          ./scripts/pytorch_install.sh ${{ matrix.torch-version }}

      - name: Install PyTorch Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          ./scripts/pytorch_install.ps1 ${{ matrix.torch-version }}

      - name: Install Opacus in Editing Mode
        run: |
          pip install -e . --default-timeout=60
          python -c "import opacus; print(opacus.__version__)"
